spring.application.name=s5-springboot-mvc-crud-db
spring.jpa.hibernate.ddl-auto=update
spring.datasource.dbcp2.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://db-1.cz0aa4ac8yyb.ap-south-1.rds.amazonaws.com:3306/fsad-s5
spring.datasource.username=admin
spring.datasource.password=admin123456
spring.jpa.show-sql=true
